#!/bin/bash

echo "🎮 GAMEPAD PAIRING GUIDE"
echo "========================"
echo ""
echo "Your gamepad is in pairing mode. Follow these steps:"
echo ""
echo "1. Open System Settings (click Apple menu > System Settings)"
echo ""
echo "2. Click 'Bluetooth' in the sidebar"
echo ""
echo "3. Look for 'Gamepad-igs' in the device list"
echo "   (It should appear under 'Other Devices' or 'Nearby Devices')"
echo ""
echo "4. Click on 'Gamepad-igs' when it appears"
echo ""
echo "5. Wait for pairing to complete"
echo ""
echo "6. After pairing, click the 'i' (info) button next to it"
echo "   and check that it shows 'Game Controller' as the type"
echo ""
echo "⚠️  IMPORTANT: If it shows 'AppleTrackpad' or 'Headset':"
echo "   - Disconnect the gamepad"
echo "   - Put it in XInput mode (if available)"
echo "   - Re-pair it"
echo ""
echo "After pairing, run this command to verify:"
echo "   python3 check_fix_progress.py"
echo ""
echo "Press Enter when you've completed pairing..."
read -p ""

echo ""
echo "Checking pairing status..."
python3 check_fix_progress.py