#!/usr/bin/env python3
"""
Quick Smart AI CLI Deployment using working providers
Uses Gemma2:2b via Ollama for fast local development
"""

import asyncio
import sys
from pathlib import Path

# Add TreeQuest paths
sys.path.append('/Users/Subho/CascadeProjects/enhanced-treequest')
sys.path.append('/Users/Subho/CascadeProjects/multi-ai-treequest')

from enhanced_treequest_controller import (
    EnhancedTreeQuestController, TaskRequest, TaskComplexity, TaskType, ProviderStrength
)

async def create_enhanced_cli_main():
    """Create main CLI entry point using Gemma2"""
    print("🚀 Creating enhanced CLI main entry point...")
    
    prompt = """Create a modern Python CLI entry point for Smart AI that:
1. Uses argparse with subcommands (ask, chat, providers, config)
2. Implements proper error handling and logging
3. Supports --verbose and --format flags
4. Has comprehensive help system
5. Integrates with existing smart_ai_backend.py

The CLI should replace the current flag-based interface with subcommands:
- smart-ai ask "question" 
- smart-ai chat
- smart-ai providers list
- smart-ai config get/set

Use Python 3.8+ compatible code with proper imports."""

    controller = EnhancedTreeQuestController()
    
    # Try Ollama first (local Gemma)
    if 'ollama' in controller.all_wrappers:
        print("🔄 Using Ollama with Gemma2:2b...")
        task = TaskRequest(
            prompt=prompt,
            task_type=TaskType.BACKEND,
            priority=ProviderStrength.SPEED,
            speed_requirement='normal'
        )
        
        result = await controller.execute_single_provider(task, 'ollama')
        
        if result.success and len(result.content) > 500:
            print("✅ CLI main entry point generated successfully!")
            
            # Save the code
            project_dir = Path("/Users/Subho/smart-ai-enhanced")
            project_dir.mkdir(exist_ok=True)
            
            main_file = project_dir / "smart_ai_enhanced.py"
            
            # Extract Python code from response
            content = result.content
            if "```python" in content:
                lines = content.split('\n')
                code_lines = []
                in_code_block = False
                
                for line in lines:
                    if line.strip().startswith("```python"):
                        in_code_block = True
                        continue
                    elif line.strip() == "```" and in_code_block:
                        in_code_block = False
                        continue
                    elif in_code_block:
                        code_lines.append(line)
                
                if code_lines:
                    code_content = '\n'.join(code_lines)
                    
                    # Add header and imports
                    full_content = f'''#!/usr/bin/env python3
"""
Smart AI Enhanced CLI
Generated by TreeQuest deployment system using Gemma2:2b
Enhanced version of the Smart AI CLI with subcommands and better UX
"""

{code_content}

if __name__ == "__main__":
    import sys
    sys.exit(main())
'''
                    
                    with open(main_file, 'w') as f:
                        f.write(full_content)
                    
                    # Make executable
                    import os
                    os.chmod(main_file, 0o755)
                    
                    print(f"💾 Enhanced CLI saved to: {main_file}")
                    print("📊 Generation stats:")
                    print(f"   Provider: {result.provider}")
                    print(f"   Execution time: {result.execution_time:.1f}s")
                    print(f"   Content length: {len(result.content)} chars")
                    
                    return main_file
            
            # If no code blocks, save as-is
            with open(main_file, 'w') as f:
                f.write(content)
            return main_file
        else:
            print("❌ Failed to generate CLI with Ollama")
    
    # Try other available providers
    for provider in ['groq', 'gemini', 'together', 'mistral']:
        if provider in controller.all_wrappers:
            print(f"🔄 Trying {provider}...")
            result = await controller.execute_single_provider(task, provider)
            if result.success:
                print(f"✅ Success with {provider}!")
                # Save and return similar to above
                break
    
    return None

async def create_config_manager():
    """Create configuration management system"""
    print("🔧 Creating configuration manager...")
    
    prompt = """Create a Python configuration manager class that:
1. Implements hierarchical configuration (CLI flags > env vars > config files > defaults)
2. Uses secure credential storage with keyring
3. Supports profiles/presets (development, production, offline)
4. Has environment variable integration
5. Validates configuration values

Include methods for:
- get_config(key, default=None)
- set_config(key, value)
- load_profile(name)
- save_profile(name, config)
- secure credential management

Use modern Python patterns with type hints."""
    
    controller = EnhancedTreeQuestController()
    task = TaskRequest(
        prompt=prompt,
        task_type=TaskType.BACKEND,
        priority=ProviderStrength.BALANCE
    )
    
    # Use best available provider
    for provider in ['ollama', 'groq', 'gemini']:
        if provider in controller.all_wrappers:
            result = await controller.execute_single_provider(task, provider)
            if result.success:
                print(f"✅ Config manager created with {provider}")
                
                # Save to file
                config_dir = Path("/Users/Subho/smart-ai-enhanced/src/config")
                config_dir.mkdir(parents=True, exist_ok=True)
                
                config_file = config_dir / "config_manager.py"
                with open(config_file, 'w') as f:
                    f.write(f"# Configuration Manager\n# Generated using {provider}\n\n")
                    f.write(result.content)
                
                print(f"💾 Config manager saved to: {config_file}")
                return config_file
    
    return None

async def create_provider_selector():
    """Create intelligent provider selection system"""
    print("🎯 Creating provider selector...")
    
    prompt = """Create an intelligent provider selector class that:
1. Scores providers based on task requirements, history, and performance
2. Implements fallback chains with circuit breaker pattern
3. Tracks success rates and response times
4. Has task-specific routing (coding -> Claude, speed -> Cerebras, etc.)
5. Supports cost-based selection

Include methods:
- select_optimal_provider(task_prompt, requirements)
- update_provider_metrics(provider, success, time, cost)
- get_fallback_chain(primary_provider)
- check_provider_health(provider)

Use machine learning-like scoring algorithm."""
    
    controller = EnhancedTreeQuestController()
    task = TaskRequest(
        prompt=prompt,
        task_type=TaskType.BACKEND,
        priority=ProviderStrength.ACCURACY
    )
    
    for provider in ['ollama', 'groq', 'gemini']:
        if provider in controller.all_wrappers:
            result = await controller.execute_single_provider(task, provider)
            if result.success:
                print(f"✅ Provider selector created with {provider}")
                
                # Save to file
                providers_dir = Path("/Users/Subho/smart-ai-enhanced/src/providers")
                providers_dir.mkdir(parents=True, exist_ok=True)
                
                selector_file = providers_dir / "provider_selector.py"
                with open(selector_file, 'w') as f:
                    f.write(f"# Intelligent Provider Selector\n# Generated using {provider}\n\n")
                    f.write(result.content)
                
                print(f"💾 Provider selector saved to: {selector_file}")
                return selector_file
    
    return None

async def create_response_cache():
    """Create response caching system"""
    print("💾 Creating response cache...")
    
    prompt = """Create a response caching system that:
1. Implements TTL-based caching with automatic expiration
2. Uses semantic similarity for cache hits (vector embeddings)
3. Has cache size limits with LRU eviction
4. Supports cache warming and preloading
5. Thread-safe operations

Include methods:
- get_cached_response(prompt, similarity_threshold=0.8)
- cache_response(prompt, response, ttl=3600)
- clear_cache()
- get_cache_stats()
- warm_cache(common_prompts)

Use efficient data structures and consider memory usage."""
    
    controller = EnhancedTreeQuestController()
    task = TaskRequest(
        prompt=prompt,
        task_type=TaskType.PERFORMANCE,
        priority=ProviderStrength.BALANCE
    )
    
    for provider in ['ollama', 'groq']:
        if provider in controller.all_wrappers:
            result = await controller.execute_single_provider(task, provider)
            if result.success:
                print(f"✅ Response cache created with {provider}")
                
                # Save to file
                utils_dir = Path("/Users/Subho/smart-ai-enhanced/src/utils")
                utils_dir.mkdir(parents=True, exist_ok=True)
                
                cache_file = utils_dir / "response_cache.py"
                with open(cache_file, 'w') as f:
                    f.write(f"# Response Caching System\n# Generated using {provider}\n\n")
                    f.write(result.content)
                
                print(f"💾 Response cache saved to: {cache_file}")
                return cache_file
    
    return None

async def create_integration_script():
    """Create integration script to merge with existing smart-ai"""
    print("🔗 Creating integration script...")
    
    integration_content = '''#!/usr/bin/env python3
"""
Smart AI Enhanced Integration Script
Merges enhanced CLI components with existing smart-ai installation
"""

import os
import shutil
import sys
from pathlib import Path

def backup_existing():
    """Create backup of existing smart-ai"""
    existing = Path("/Users/Subho/smart-ai")
    backup = Path("/Users/Subho/smart-ai-backup")
    
    if existing.exists():
        print("💾 Creating backup...")
        if backup.exists():
            shutil.rmtree(backup)
        shutil.copytree(existing, backup)
        print(f"✅ Backup created at: {backup}")

def integrate_enhanced():
    """Integrate enhanced components"""
    enhanced_dir = Path("/Users/Subho/smart-ai-enhanced")
    target_dir = Path("/Users/Subho")
    
    print("🔄 Integrating enhanced components...")
    
    # Copy enhanced main CLI
    if (enhanced_dir / "smart_ai_enhanced.py").exists():
        shutil.copy2(
            enhanced_dir / "smart_ai_enhanced.py",
            target_dir / "smart-ai-enhanced"
        )
        os.chmod(target_dir / "smart-ai-enhanced", 0o755)
        print("✅ Enhanced CLI installed as 'smart-ai-enhanced'")
    
    # Copy supporting modules
    if (enhanced_dir / "src").exists():
        target_src = target_dir / "smart-ai-enhanced-modules"
        if target_src.exists():
            shutil.rmtree(target_src)
        shutil.copytree(enhanced_dir / "src", target_src)
        print("✅ Supporting modules copied")
    
    print("🎉 Integration completed!")
    print("Usage:")
    print("  smart-ai-enhanced ask 'your question'")
    print("  smart-ai-enhanced chat")
    print("  smart-ai-enhanced providers list")

def main():
    backup_existing()
    integrate_enhanced()

if __name__ == "__main__":
    main()
'''
    
    enhanced_dir = Path("/Users/Subho/smart-ai-enhanced")
    integration_file = enhanced_dir / "integrate.py"
    
    with open(integration_file, 'w') as f:
        f.write(integration_content)
    
    os.chmod(integration_file, 0o755)
    print(f"🔗 Integration script created: {integration_file}")
    return integration_file

async def quick_deploy():
    """Deploy core improvements quickly using local models"""
    print("🚀 Smart AI Quick Deployment Starting...")
    print("=" * 50)
    
    results = []
    
    # Deploy core components
    components = [
        ("Enhanced CLI Main", create_enhanced_cli_main),
        ("Configuration Manager", create_config_manager), 
        ("Provider Selector", create_provider_selector),
        ("Response Cache", create_response_cache),
        ("Integration Script", create_integration_script)
    ]
    
    for name, create_func in components:
        print(f"\n🔄 Deploying: {name}")
        try:
            result = await create_func()
            if result:
                results.append((name, True, str(result)))
                print(f"✅ {name} deployed successfully")
            else:
                results.append((name, False, "Generation failed"))
                print(f"❌ {name} deployment failed")
        except Exception as e:
            results.append((name, False, str(e)))
            print(f"❌ {name} error: {e}")
    
    # Summary
    print("\n" + "=" * 50)
    print("🎉 QUICK DEPLOYMENT SUMMARY")
    print("=" * 50)
    
    successful = sum(1 for _, success, _ in results if success)
    total = len(results)
    
    print(f"📊 Success Rate: {successful}/{total} ({successful/total:.1%})")
    
    for name, success, detail in results:
        status = "✅" if success else "❌"
        print(f"{status} {name}: {detail}")
    
    if successful > 0:
        print("\n🔗 To integrate with existing smart-ai:")
        print("   cd /Users/Subho/smart-ai-enhanced")
        print("   python3 integrate.py")
        print("\n🚀 To test enhanced CLI:")
        print("   smart-ai-enhanced ask 'Hello world'")

if __name__ == "__main__":
    asyncio.run(quick_deploy())