#!/usr/bin/env python3
"""
Refine weak word-level laughter labels with a local assistant model.

Recommended local model on 8GB hardware:
- nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF

This script does not assume a specific runner. It supports:
- OpenAI-compatible local servers (LM Studio, llama.cpp server, vLLM-compatible)
- Ollama's generate API

Input:
- JSONL generated by convert_standup_raw_to_word_level.py

Output:
- refined JSONL with updated labels
- audit log JSONL with model decisions

The local model is used as a teacher. It decides whether the current weak label
is plausible and, if so, which word index most likely triggers the audience
laughter.
"""

from __future__ import annotations

import argparse
import json
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set
from urllib import error, request


PROMPT_VERSION = "lexical_target_v2"


SYSTEM_PROMPT = """You are refining weak labels for stand-up comedy laughter prediction.
You receive a tokenized stand-up segment where audience laughter follows shortly after the line.
Return strict JSON only.

Rules:
- Select the single word index most likely responsible for triggering the laughter.
- If the line does not contain a clear trigger word or phrase, return action=drop.
- Prefer punchline words, reversals, callbacks, and surprise terms over setup words.
- Prefer a content-bearing lexical word inside the punchline phrase, not a pronoun, determiner, auxiliary, or punctuation token.
- If a phrase matters, choose the most informative single word inside that phrase.
- Avoid tokens like quotes, apostrophes, commas, question marks, and generic words like I, you, my, the, a, an, this, that, it unless there is no better lexical target.
- Confidence must be between 0 and 1.
- In note, quote the exact chosen word in single quotes.
- Do not explain outside JSON.

JSON schema:
{"action":"keep"|"drop","target_word_index":integer|null,"confidence":number,"reason_tags":["..."],"note":"..."}
"""


@dataclass(slots=True)
class RefinementConfig:
    backend: str
    endpoint: str
    model: str
    timeout_seconds: float
    min_confidence: float
    max_examples: Optional[int]
    sleep_seconds: float
    tail_window: int
    write_every: int
    progress_every: int
    resume: bool


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Refine weak laughter labels with a local assistant model.")
    parser.add_argument("--input-file", type=Path, required=True, help="Weak-label JSONL input.")
    parser.add_argument("--output-file", type=Path, required=True, help="Refined JSONL output.")
    parser.add_argument("--audit-file", type=Path, required=True, help="Decision log JSONL output.")
    parser.add_argument(
        "--backend",
        choices=["openai", "ollama"],
        default="openai",
        help="Inference backend.",
    )
    parser.add_argument(
        "--endpoint",
        default="http://127.0.0.1:1234/v1/chat/completions",
        help="Backend endpoint. For Ollama, use http://127.0.0.1:11434/api/generate",
    )
    parser.add_argument(
        "--model",
        default="nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
        help="Local model identifier used by the serving backend.",
    )
    parser.add_argument("--timeout-seconds", type=float, default=60.0)
    parser.add_argument("--min-confidence", type=float, default=0.6)
    parser.add_argument("--max-examples", type=int, default=None)
    parser.add_argument("--sleep-seconds", type=float, default=0.0)
    parser.add_argument(
        "--tail-window",
        type=int,
        default=24,
        help="Only show the last N words to the teacher to focus on the punchline region.",
    )
    parser.add_argument(
        "--write-every",
        type=int,
        default=25,
        help="Persist refined and audit rows every N processed examples.",
    )
    parser.add_argument(
        "--progress-every",
        type=int,
        default=10,
        help="Print progress every N processed examples.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume from an existing audit file instead of truncating outputs first.",
    )
    return parser.parse_args()


def load_jsonl(path: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            rows.append(json.loads(line))
    return rows


def write_jsonl(path: Path, rows: Iterable[Dict[str, Any]]) -> int:
    count = 0
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=True) + "\n")
            count += 1
    return count


def append_jsonl(path: Path, rows: Iterable[Dict[str, Any]]) -> int:
    count = 0
    with path.open("a", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=True) + "\n")
            count += 1
    return count


def count_jsonl_rows(path: Path) -> int:
    if not path.exists():
        return 0
    return sum(1 for line in path.read_text(encoding="utf-8").splitlines() if line.strip())


def load_processed_example_ids(path: Path) -> Set[str]:
    if not path.exists():
        return set()

    processed_ids: Set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        example_id = row.get("example_id")
        if example_id:
            processed_ids.add(str(example_id))
    return processed_ids


def post_json(url: str, payload: Dict[str, Any], timeout_seconds: float) -> Dict[str, Any]:
    body = json.dumps(payload).encode("utf-8")
    http_request = request.Request(
        url=url,
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with request.urlopen(http_request, timeout=timeout_seconds) as response:
        data = response.read().decode("utf-8")
    return json.loads(data)


def extract_json_object(text: str) -> Dict[str, Any]:
    stripped = text.strip()
    try:
        return json.loads(stripped)
    except json.JSONDecodeError:
        pass

    start = stripped.find("{")
    end = stripped.rfind("}")
    if start >= 0 and end > start:
        return json.loads(stripped[start : end + 1])
    raise ValueError("Model response did not contain valid JSON.")


def call_openai_compatible(config: RefinementConfig, prompt: str) -> Dict[str, Any]:
    payload = {
        "model": config.model,
        "temperature": 0.0,
        "max_tokens": 220,
        "response_format": {"type": "json_object"},
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
    }
    response = post_json(config.endpoint, payload, timeout_seconds=config.timeout_seconds)
    content = response["choices"][0]["message"]["content"]
    return extract_json_object(content)


def call_ollama(config: RefinementConfig, prompt: str) -> Dict[str, Any]:
    payload = {
        "model": config.model,
        "prompt": SYSTEM_PROMPT + "\n\n" + prompt,
        "stream": False,
        "format": "json",
        "options": {"temperature": 0},
    }
    response = post_json(config.endpoint, payload, timeout_seconds=config.timeout_seconds)
    content = response.get("response", "")
    return extract_json_object(content)


def call_model(config: RefinementConfig, prompt: str) -> Dict[str, Any]:
    if config.backend == "ollama":
        return call_ollama(config, prompt)
    return call_openai_compatible(config, prompt)


def build_prompt(example: Dict[str, Any], tail_window: int) -> str:
    words = list(example["words"])
    labels = list(example["labels"])
    positive_index = next((index for index, label in enumerate(labels) if label == 1), None)
    view_start = max(0, len(words) - tail_window)
    visible_words = words[view_start:]
    visible_indices = list(range(view_start, len(words)))

    indexed_words = "\n".join(
        f"{index}: {word}"
        for index, word in zip(visible_indices, visible_words)
    )

    metadata = example.get("metadata") or {}
    return (
        f"Example ID: {example.get('example_id')}\n"
        f"Language: {example.get('language', 'en')}\n"
        f"Weak positive index: {positive_index}\n"
        f"Laughter tag after line: {metadata.get('next_laughter_tag')}\n"
        f"Laughter type: {metadata.get('laughter_type')}\n"
        f"Indexed words:\n{indexed_words}\n\n"
        "Task: return the single best target word index for laughter triggering.\n"
        "Choose one content-bearing lexical word, not punctuation or a generic stopword, unless no better target exists.\n"
        "If the funniest part is a phrase, pick the strongest single lexical word inside it and quote that exact word in note."
    )


def normalize_decision(raw: Dict[str, Any]) -> Dict[str, Any]:
    action = str(raw.get("action") or "drop").strip().lower()
    if action not in {"keep", "drop"}:
        action = "drop"
    target_word_index = raw.get("target_word_index")
    if target_word_index is not None:
        try:
            target_word_index = int(target_word_index)
        except (TypeError, ValueError):
            target_word_index = None
    confidence = raw.get("confidence", 0.0)
    try:
        confidence = float(confidence)
    except (TypeError, ValueError):
        confidence = 0.0
    return {
        "action": action,
        "target_word_index": target_word_index,
        "confidence": max(0.0, min(1.0, confidence)),
        "reason_tags": [str(item) for item in raw.get("reason_tags", [])][:8],
        "note": str(raw.get("note") or ""),
    }


def apply_decision(example: Dict[str, Any], decision: Dict[str, Any], min_confidence: float) -> Optional[Dict[str, Any]]:
    labels = [0] * len(example["labels"])
    if (
        decision["action"] != "keep"
        or decision["target_word_index"] is None
        or decision["confidence"] < min_confidence
        or decision["target_word_index"] < 0
        or decision["target_word_index"] >= len(labels)
    ):
        return None

    labels[decision["target_word_index"]] = 1
    refined = dict(example)
    refined["labels"] = labels
    metadata = dict(refined.get("metadata") or {})
    metadata.update(
        {
            "teacher_model": decision.get("teacher_model"),
            "teacher_backend": decision.get("teacher_backend"),
            "teacher_prompt_version": decision.get("prompt_version"),
            "teacher_confidence": decision["confidence"],
            "teacher_reason_tags": decision["reason_tags"],
            "teacher_note": decision["note"],
            "teacher_target_word_index": decision["target_word_index"],
            "label_refinement": "nemotron_teacher",
        }
    )
    refined["metadata"] = metadata
    return refined


def refine_dataset(
    rows: Sequence[Dict[str, Any]],
    config: RefinementConfig,
    output_file: Path,
    audit_file: Path,
) -> Dict[str, Any]:
    selected_rows = list(rows[: config.max_examples] if config.max_examples else rows)
    processed_ids = load_processed_example_ids(audit_file) if config.resume else set()

    if not config.resume:
        output_file.write_text("", encoding="utf-8")
        audit_file.write_text("", encoding="utf-8")

    starting_output_examples = count_jsonl_rows(output_file)
    pending_rows = [row for row in selected_rows if str(row.get("example_id")) not in processed_ids]
    refined_buffer: List[Dict[str, Any]] = []
    audit_buffer: List[Dict[str, Any]] = []
    kept_examples = starting_output_examples
    processed_examples = len(processed_ids)

    print(
        json.dumps(
            {
                "input_examples": len(selected_rows),
                "resume": config.resume,
                "already_processed": len(processed_ids),
                "pending_examples": len(pending_rows),
                "write_every": config.write_every,
            }
        ),
        flush=True,
    )

    for row in pending_rows:
        prompt = build_prompt(row, tail_window=config.tail_window)
        started_at = time.time()
        try:
            raw_decision = call_model(config, prompt)
            decision = normalize_decision(raw_decision)
            decision["teacher_model"] = config.model
            decision["teacher_backend"] = config.backend
            decision["prompt_version"] = PROMPT_VERSION
            decision["latency_seconds"] = round(time.time() - started_at, 3)
        except (ValueError, KeyError, error.URLError, TimeoutError) as exc:
            decision = {
                "action": "drop",
                "target_word_index": None,
                "confidence": 0.0,
                "reason_tags": ["request_error"],
                "note": str(exc),
                "teacher_model": config.model,
                "teacher_backend": config.backend,
                "prompt_version": PROMPT_VERSION,
                "latency_seconds": round(time.time() - started_at, 3),
            }

        refined = apply_decision(row, decision, min_confidence=config.min_confidence)
        if refined is not None:
            refined_buffer.append(refined)
            kept_examples += 1

        audit_buffer.append(
            {
                "example_id": row.get("example_id"),
                "decision": decision,
                "kept": refined is not None,
                "weak_positive_index": next(
                    (index for index, label in enumerate(row.get("labels", [])) if label == 1),
                    None,
                ),
            }
        )
        processed_examples += 1

        if len(audit_buffer) >= config.write_every:
            if refined_buffer:
                append_jsonl(output_file, refined_buffer)
                refined_buffer.clear()
            append_jsonl(audit_file, audit_buffer)
            audit_buffer.clear()

        if config.progress_every > 0 and processed_examples % config.progress_every == 0:
            print(
                json.dumps(
                    {
                        "processed_examples": processed_examples,
                        "input_examples": len(selected_rows),
                        "kept_examples": kept_examples,
                        "dropped_examples": processed_examples - kept_examples,
                    }
                ),
                flush=True,
            )

        if config.sleep_seconds > 0:
            time.sleep(config.sleep_seconds)

    if refined_buffer:
        append_jsonl(output_file, refined_buffer)
    if audit_buffer:
        append_jsonl(audit_file, audit_buffer)

    return {
        "summary": {
            "input_examples": len(selected_rows),
            "processed_examples": processed_examples,
            "output_examples": kept_examples,
            "dropped_examples": processed_examples - kept_examples,
            "backend": config.backend,
            "model": config.model,
            "min_confidence": config.min_confidence,
            "resume": config.resume,
        },
    }


def main() -> None:
    args = parse_args()
    config = RefinementConfig(
        backend=args.backend,
        endpoint=args.endpoint,
        model=args.model,
        timeout_seconds=args.timeout_seconds,
        min_confidence=args.min_confidence,
        max_examples=args.max_examples,
        sleep_seconds=args.sleep_seconds,
        tail_window=args.tail_window,
        write_every=max(1, args.write_every),
        progress_every=max(0, args.progress_every),
        resume=args.resume,
    )
    rows = load_jsonl(args.input_file)
    args.output_file.parent.mkdir(parents=True, exist_ok=True)
    args.audit_file.parent.mkdir(parents=True, exist_ok=True)
    result = refine_dataset(rows, config=config, output_file=args.output_file, audit_file=args.audit_file)
    print(json.dumps(result["summary"], indent=2))


if __name__ == "__main__":
    main()
